# This file provides instructions for packaging.

`MooseX-Prototype`
	perl_version_from m`MooseX::Prototype`;
	version_from      m`MooseX::Prototype`;
	readme_from       m`MooseX::Prototype`;
	test_requires     p`Test::More 0.61` ;
	requires          p`Moose 2.00`;
	requires          p`Sub::Exporter`;
	requires          p`Data::OptList`;
	requires          p`thanks`;
.

